on:
  issues:
    types: [created]
  issue_comment:
    types: [created, edited, updated]

jobs:
  
  add_comment_job:
    runs-on: ubuntu-latest
    steps:
    - uses: jamsajones/external-comments-labeler@master
      with: 
        label: "Answer Please"
        githubToken: "${{ secrets.GITHUB_TOKEN }}"
