on:
  issue_comment:
    types: [created, edited]

jobs:
  
  add_comment_job:
    runs-on: ubuntu-latest
    steps:
    - uses: jamsajones/external-comments-labeler@master
      with: 
        label: "Answer Please"
        orgs: "sportsApp"
        githubToken: "${{ secrets.GITHUB_TOKEN }}"
